version: "3"

services:
  wordpress:
    build: ./docker
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./themes/design:/var/www/html/wp-content/themes/design
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress